# Package manager
[[plugins]]
repo = 'Shougo/dein.vim'

##### INTERFACE #####

# Color theme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

# Status bar
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.vim'

##### RUNTIME #####

# Asynchronous execution library
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'  # Linux & macOS only

##### EDITOR #####

# Highlight all trailing whitespace characters
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = '''
  let g:better_whitespace_enabled=0
'''

# Read/Write files with `sudo` command
[[plugins]]
repo = 'lambdalisue/suda.vim'

# Visually display indent levels
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  set ts=4 sw=4 et
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
  let g:indent_guides_tab_guides = 0
'''

# Surround
[[plugins]]
repo = 'tpope/vim-surround'

# Syntax checking
[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'source ~/.vim/rc/plugins/syntastic.vim'

# Autocompletion framework 
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  source ~/.vim/rc/plugins/deoplete.vim
'''

# Snippet support
#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#hook_add = '''
#  source ~/.vim/rc/plugins/neosnippet.vim
#'''
#
#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsExpandTrigger="<c-k>"
  let g:UltiSnipsJumpForwardTrigger="<c-n>"
  let g:UltiSnipsJumpBackwardTrigger="<c-p>"
'''

[[plugins]]
repo = 'honza/vim-snippets'

##### SOURCE CONTROL #####

# Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'autocmd QuickFixCmdPost *grep* cwindow'

# Shows a git diff in the gutter
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=1000
'''

##### FUZZY FINDER #####

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'source ~/.vim/rc/plugins/fzf.vim'
