# Package manager
[[plugins]]
repo = 'Shougo/dein.vim'

##### INTERFACE #####

# Color theme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = 'source ~/.vim/rc/plugins/gruvbox-material.rc.vim'

# Font / icon
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# Status bar
# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = 'source ~/.vim/rc/plugins/lightline.vim'


[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'source ~/.vim/rc/plugins/lualine.rc.vim'

##### RUNTIME #####

# Asynchronous execution library
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make' # Linux & macOS only

##### EDITOR #####

# Highlight all trailing whitespace characters
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = 'let g:better_whitespace_enabled=0'

# Read/Write files with `sudo` command
[[plugins]]
repo = 'lambdalisue/suda.vim'

# Indent
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'

# Registers
[[plugins]]
repo = 'junegunn/vim-peekaboo'

# auto closing brackets
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# Surround
[[plugins]]
repo = 'tpope/vim-surround'

# Syntax checking
[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'source ~/.vim/rc/plugins/syntastic.vim'

# scrolling
[[plugins]]
repo = 'psliwka/vim-smoothie'

# startup page
[[plugins]]
repo = 'mhinz/vim-startify'

# readline key bindings, necessary for tmux-yank
[[plugins]]
repo = 'tpope/vim-rsi'

# vista
[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = 'source ~/.vim/rc/plugins/vista.vim'

# nvim-treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = 'source ~/.vim/rc/plugins/treesitter.rc.vim'
hook_post_update = 'TSUpdate'


# required by vim-markdown
[[plugins]]
repo = 'godlygeek/tabular'

##### SOURCE CONTROL #####

# Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'autocmd QuickFixCmdPost *grep* cwindow'

# Shows a git diff in the gutter
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'rhysd/conflict-marker.vim'

##### FUZZY FINDER #####

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'source ~/.vim/rc/plugins/fzf.vim'

##### AUTOCOMPLETION #####

### Github Copilot
[[plugins]]
repo = 'github/copilot.vim'
hook_add = 'source ~/.vim/rc/plugins/copilot.rc.vim'

## coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = 'source ~/.vim/rc/plugins/coc.rc.vim'

# [[plugins]]
# repo = 'josa42/vim-lightline-coc'

##### DB #####
[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'

##### TELESCOPE #####
[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = "source ~/.vim/rc/plugins/telescope.rc.vim"

[[plugins]]
repo = 'nvim-telescope/telescope-media-files.nvim'
hook_add = "lua require('telescope').load_extension('media_files')"

[[plugins]]
repo = 'nvim-telescope/telescope-symbols.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
hook_add = "lua require('telescope').load_extension('file_browser')"

[[plugins]]
repo = 'fannheyward/telescope-coc.nvim'
hook_add = "lua require('telescope').load_extension('coc')"

##### TELEKASTEN #####
[[plugins]]
repo = 'renerocksai/telekasten.nvim'
hook_add = 'source ~/.vim/rc/plugins/telekasten.rc.vim'

[[plugins]]
repo = 'renerocksai/calendar-vim'
