# Package manager
[[plugins]]
repo = 'Shougo/dein.vim'

##### INTERFACE #####

# Color theme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

# Status bar
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.vim'

##### RUNTIME #####

# Asynchronous execution library
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'  # Linux & macOS only

##### EDITOR #####

# Highlight all trailing whitespace characters
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

# Read/Write files with `sudo` command
[[plugins]]
repo = 'lambdalisue/suda.vim'

# Visually display indent levels
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  set ts=4 sw=4 et
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
  let g:indent_guides_tab_guides = 0
'''

# auto closing brackets
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# Surround
[[plugins]]
repo = 'tpope/vim-surround'

# Syntax checking
[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = 'source ~/.vim/rc/plugins/syntastic.vim'

# scrolling
[[plugins]]
repo = 'psliwka/vim-smoothie'

# startup page
[[plugins]]
repo = 'mhinz/vim-startify'

# readline key bindings, necessary for tmux-yank
[[plugins]]
repo = 'tpope/vim-rsi'

# vista
[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = 'source ~/.vim/rc/plugins/vista.vim'

##### SOURCE CONTROL #####

# Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'autocmd QuickFixCmdPost *grep* cwindow'

# Shows a git diff in the gutter
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'


##### FUZZY FINDER #####

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'source ~/.vim/rc/plugins/fzf.vim'

##### AUTOCOMPLETION #####

### Github Copilot
[[plugins]]
repo = 'github/copilot.vim'

## coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = 'source ~/.vim/rc/plugins/coc.rc.vim'

[[plugins]]
repo = 'josa42/vim-lightline-coc'

##### DB #####
[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'
