[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'let g:NERDTreeNodeDelimiter = "\u00a0"'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_source = 'source ~/.vim/rc/plugins/quickrun.vim'
