# Package manager
[[plugins]]
repo = 'Shougo/dein.vim'

##### PREREQ #####
# plugins that are required by many
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'rcarriga/nvim-notify'
hook_add = 'source ~/.vim/rc/plugins/notify.lua'

##### INTERFACE #####

# Color theme
[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
hook_add = 'source ~/.vim/rc/plugins/gruvbox-material.rc.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

# Font / icon
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# [[plugins]]
# repo = 'wellle/context.vim'

#### MOVEMENT ####

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'ggandor/leap.nvim'
hook_add = 'lua require("leap").add_default_mappings()'


##### RUNTIME #####

# Asynchronous execution library
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'              # Linux & macOS only

[[plugins]]
repo = 'gelguy/wilder.nvim'
hook_add = 'source ~/.vim/rc/plugins/wilder.rc.lua'

##### EDITOR #####

# Highlight all trailing whitespace characters
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
hook_add = 'let g:better_whitespace_enabled=0'

# Read/Write files with `sudo` command
[[plugins]]
repo = 'lambdalisue/suda.vim'

# Indent
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'

# Registers
[[plugins]]
repo = 'junegunn/vim-peekaboo'

# auto closing brackets
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# Surround
[[plugins]]
repo = 'tpope/vim-surround'

# scrolling
[[plugins]]
repo = 'petertriho/nvim-scrollbar'
hook_add = 'source ~/.vim/rc/plugins/scrollbar.rc.lua'

[[plugins]]
repo = 'karb94/neoscroll.nvim'
hook_add = 'lua require("neoscroll").setup()'

# startup page
[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = 'source ~/.vim/rc/plugins/startify.rc.vim'

# readline key bindings, necessary for tmux-yank
[[plugins]]
repo = 'tpope/vim-rsi'

# vista
#[[plugins]]
#repo = 'liuchengxu/vista.vim'
#hook_add = 'source ~/.vim/rc/plugins/vista.vim'

# required by vim-markdown
[[plugins]]
repo = 'godlygeek/tabular'

# comments
[[plugins]]
repo = 'numToStr/Comment.nvim'
hook_add = 'lua require("Comment").setup()'

# todo comments
[[plugins]]
repo = 'folke/todo-comments.nvim'
hook_add = 'source ~/.vim/rc/plugins/todo-comments.rc.lua'

# search lens
[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
hook_add = 'source ~/.vim/rc/plugins/hlslens.rc.lua'

##### SOURCE CONTROL #####

# Git wrapper
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'autocmd QuickFixCmdPost *grep* cwindow'

[[plugins]]
repo = 'sindrets/diffview.nvim'
hook_add = 'source ~/.vim/rc/plugins/diffview.rc.vim'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = """
    lua require('gitsigns').setup()
"""

[[plugins]]
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'rhysd/conflict-marker.vim'

[[plugins]]
repo = 'ruanyl/vim-gh-line'

##### FUZZY FINDER #####

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'source ~/.vim/rc/plugins/fzf.vim'

[[plugins]]
repo = 'stsewd/fzf-checkout.vim'

##### AUTOCOMPLETION #####

### Github Copilot
[[plugins]]
repo = 'github/copilot.vim'
hook_add = 'source ~/.vim/rc/plugins/copilot.rc.vim'

## coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = 'source ~/.vim/rc/plugins/coc.rc.vim'

##### DB #####
[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'

##### TELESCOPE #####
[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = "source ~/.vim/rc/plugins/telescope.rc.vim"

[[plugins]]
repo = 'nvim-telescope/telescope-media-files.nvim'
hook_add = "lua require('telescope').load_extension('media_files')"

[[plugins]]
repo = 'nvim-telescope/telescope-symbols.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
hook_add = "lua require('telescope').load_extension('file_browser')"

[[plugins]]
repo = 'fannheyward/telescope-coc.nvim'
hook_add = "lua require('telescope').load_extension('coc')"

##### TELEKASTEN #####
[[plugins]]
repo = 'renerocksai/telekasten.nvim'
hook_add = 'source ~/.vim/rc/plugins/telekasten.rc.vim'

[[plugins]]
repo = 'renerocksai/calendar-vim'


##### LUALINE #####
# calling at the bottom to ensure everything else was loaded
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'source ~/.vim/rc/plugins/lualine.rc.lua'

[[plugins]]
repo = 'akinsho/bufferline.nvim'
hook_add = 'source ~/.vim/rc/plugins/bufferline.rc.lua'

##### DUCK #####
[[plugins]]
repo = 'tamton-aquib/duck.nvim'

##### OUTLINE #####
# nvim-treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'
hook_source = 'source ~/.vim/rc/plugins/treesitter.rc.lua'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter-context'
hook_source = 'lua require("treesitter-context").setup()'

# outline
[[plugins]]
repo = 'stevearc/aerial.nvim'
hook_add = 'source ~/.vim/rc/plugins/aerial.rc.lua'


##### FOLDS #####
[[plugins]]
repo = 'kevinhwang91/promise-async'

[[plugins]]
repo = 'kevinhwang91/nvim-ufo'
hook_add = '''
source ~/.vim/rc/plugins/nvim-ufo.rc.lua
'''

#### FILE MANAGER ####
[[plugins]]
repo = 'nvim-neo-tree/neo-tree.nvim'
hook_add = 'source ~/.vim/rc/plugins/neo-tree.rc.lua'

#### TERMINAL ####
[[plugins]]
repo = 'akinsho/toggleterm.nvim'
hook_add = 'source ~/.vim/rc/plugins/toggleterm.rc.lua'

#### ZEN MODE ####
[[plugins]]
repo = 'folke/zen-mode.nvim'
hook_source = 'source ~/.vim/rc/plugins/zen-mode.rc.lua'

[[plugins]]
repo = 'folke/twilight.nvim'
hook_add = 'lua require("twilight").setup()'

#### CSV ####
[[plugins]]
repo = 'chrisbra/csv.vim'
hook_add = 'let g:csv_move_folds = 1'

#### GPT ####
[[plugins]]
repo = 'jackMort/ChatGPT.nvim'
hook_add = 'source ~/.vim/rc/plugins/chatgpt.rc.lua'
