[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/rc/plugins/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'autocmd QuickFixCmdPost *grep* cwindow'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=1000
'''

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  set ts=4 sw=4 et
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'  # Linux & macOS only

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.vim/rc/plugins/ale.vim'
