[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.vim/rc/plugins/nerdtree.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'solarnz/thrift.vim'
on_ft = 'thrift'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = 'source ~/.vim/rc/plugins/vim-go.vim'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = ['deoplete.nvim']
hook_add = 'source ~/.vim/rc/plugins/deoplete-go.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_source = 'source ~/.vim/rc/plugins/quickrun.vim'

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'
