##### FILE EXPLORER #####
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.vim/rc/plugins/nerdtree.vim'

##### EDITOR #####

# Auto close parentheses and repeat by dot dot dot ...
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# Binary editor
[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

##### RUNTIME #####
[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_source = 'source ~/.vim/rc/plugins/quickrun.vim'

##### FILE TYPE #####
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'solarnz/thrift.vim'
on_ft = 'thrift'

[[plugins]]
repo = 'tomlion/vim-solidity'
on_ft = 'sol'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'dockerfile'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

##### DB #####
[[plugins]]
repo = 'tpope/dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'
