sudo: required
services:
    - docker

# Handle git submodules
git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive


script:
    - docker build .
    - docker build ./dev/go/
    - docker build ./dev/tensorflow/
    - docker build ./dev/frida/
    - docker build ./dev/mitmproxy/
    - docker build -f=./dev/kali/Dockerfile .
    - docker build ./dev/recon/
