##### EDITOR #####
# Auto close parentheses and repeat by dot dot dot ...
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# Binary editor
[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

##### RUNTIME #####
[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_source = 'source ~/.vim/rc/plugins/quickrun.vim'

##### FILE TYPE #####
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'solarnz/thrift.vim'
on_ft = 'thrift'

[[plugins]]
repo = 'neo4j-contrib/cypher-vim-syntax'
on_ft = 'cypher'

# [[plugins]]
# repo = 'tomlion/vim-solidity'
# on_ft = 'solidity'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = 'dockerfile'

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql', 'typescript', 'javascript']

##### MARKDOWN #####

# [[plugins]]
# repo = 'preservim/vim-markdown'
# on_ft = ['markdown', 'telekasten']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'telekasten']
build = 'sh -c "cd app && yarn install"'
hook_add = 'let g:mkdp_auto_close = 0'
