FROM sirius8117/dotfiles
 
# If for whatever reason you need to use Python 2.7.

RUN sudo apt-get install python-dev python-pip -y
RUN sudo ln -sfn python2.7 /usr/bin/python
RUN sudo ln -sfn pip2 /usr/bin/pip
