FROM sirius8117/dotfiles

# Install gplaycli
# https://github.com/matlink/gplaycli
# TODO: need to set up configuration

RUN sudo apt-get update && sudo apt-get install libffi-dev libssl-dev -y
RUN pip3 install gplaycli

# Install apkcrawler
# https://github.com/opengapps/apkcrawler
